# vinterra:debug/profile/run_profile_macro
# AUTO-GENERATED BY dev/generate_profiles.py. DO NOT EDIT.
# Runs a generated profile by its generated function slug.
# Usage: function vinterra:debug/profile/run_profile_macro {test_id:"env_001"}
# Convert spreadsheet IDs manually when invoking: ENV-001 -> env_001.
# Must be executed as and at the recording player.

$function vinterra:debug/profile/generated/$(test_id)
